### ISSUE TITLE
Adding a contact adds every other contact added before that again

### ISSUE THREAD

**Issue by abhilashkakumanu1** [DwarakanathAkkala/ContactsWebApp#1]
1. Add a contact for the first time - everything works fine
2. Try adding another contact - Now you will see 3 entries in the list of added contacts
3. Try adding the third contact and now you will see 6 entries in the list of contacts

**Comment by DwarakanathAkkala** [comment]
Thanks for the test!

It was the DOM Element addition causing the issue. The logic was perfectly working fine by storing the data in local storage session.

Written separate code for Adding a single entry and fetching all the data from Local Storage Session.

Hope this should work fine now :-)

**Comment by abhilashkakumanu1** [comment]
This has created a new issue. Deleting a contact is adding everthing thats already there
@DwarakanathAkkala

**Comment by DwarakanathAkkala** [comment]
Not clearing DOM after successful deletion was the issue. Thanks for the test :-)
